services:
  app:
    image: "mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye"
    volumes:
      - ..:/workspace
    depends_on:
      - postgres
    command: sleep infinity
  postgres:
    image: postgres:alpine
    tty: true
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DATABASE_NAME:-aka}
      - POSTGRES_USER=${DATABASE_USER:-aka}
      - POSTGRES_PASSWORD=${DATABASE_PASS:-aka}
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: